### ISSUE TITLE
use gm-fabric-go release v0.1.10

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/homebrew-decipher#24]

**Comment by joshua-rutherford** [comment]
@dougfort, what is this issue for?

**Comment by joshua-rutherford** [comment]
Oh, did you mean gm-fabric-go?

**Comment by dougfort** [comment]
gm-fabric-go

## 0.1.10 (August 8th, 2018)
### Fixed
- Impersonation not using cert when reading handshake
- `tlsutil` defaulting to `tls.NoClientAuth`
